#ifndef COMPILADORES_TEXTILES_TEXTILESFLUJOPRODUCCION_H
#define COMPILADORES_TEXTILES_TEXTILESFLUJOPRODUCCION_H

#include "../Parser/Parser.h"

void TextilesFlujoProduccion();

int print_menu();

#endif //COMPILADORES_TEXTILES_TEXTILESFLUJOPRODUCCION_H
